# fly.toml app configuration file generated for expression-evaluator on 2024-05-01T23:26:32+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'expression-evaluator'
primary_region = 'otp'

[build]
  dockerfile = 'src/main/docker/Dockerfile'
  ignorefile = '.dockerignore'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
